name = "script-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "SHOT_LIST_DO"
class_name = "ShotListDurableObject"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "my-script-processor-bucket-2025"

[ai]
binding = "AI"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShotListDurableObject"]